### ISSUE TITLE
How to use it with webpack postcss loader

### ISSUE THREAD

**Issue by apreg** [morishitter/postcss-include#1]
Hi,

Could you tell me how to configure webpack's postcss plugin to use postcss-include?
Here is my config:

```
/*
 * Webpack development server configuration
 *
 * This file is set up for serving the webpak-dev-server, which will watch for changes and recompile as required if
 * the subfolder /webpack-dev-server/ is visited. Visiting the root will not automatically reload.
 */
'use strict';
var webpack = require('webpack');
var webpackPostcssTools = require('webpack-postcss-tools');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var atcss = require('atcss');

var map = webpackPostcssTools.makeVarMap('src/styles/app.css');


module.exports = {

    output: {
        filename: 'app.js',
        publicPath: '/assets/',
        path: __dirname + '/assets'
    },

    cache: true,
    debug: true,
    devtool: false,
    entry: [
        'webpack/hot/only-dev-server',
        './src/scripts/app.js'
    ],

    stats: {
        colors: true,
        reasons: true
    },

    resolve: {
        packageMains: [
            'webpack',
            'browser',
            'web',
            'browserify',
            ['jam', 'main'],
            'style',
            'main'
        ],
        extensions: ['', '.js'],
        modulesDirectories: ['node_modules', 'bower_components', 'web_modules']
    },
    module: {
        preLoaders: [{
            test: '\\.js$',
            exclude: 'node_modules',
            loader: 'jshint'
        }],
        loaders: [{
            test: /\.js$/,
            loader: 'react-hot!jsx-loader?harmony'
        }, {
            test: /\.styl/,
            loader: 'style-loader!css-loader!stylus-loader'
        }, {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract("style",
                "css?importLoaders=1!postcss"
            )
            //loader: 'style!css?importLoaders=1!postcss'
        }, {
            test: /\.(png|jpg)$/,
            loader: 'url-loader?limit=8192'
        }, {
            test: /\.woff(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "url-loader?limit=10000&minetype=application/font-woff"
        }, {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "file-loader"
        }]
    },

    postcss: [
        webpackPostcssTools.prependTildesToImports,

        require('postcss-custom-properties')({
            variables: map.vars
        }),

        require('postcss-custom-media')({
            extensions: map.media
        }),

        require('postcss-calc'),
        require('postcss-include')
    ],

    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new ExtractTextPlugin("app.css", {allChunks: true})
    ]

};

```

Although it does not throw any error in the result css I can see the definition of base classes and such. Like this:

```
.base-1 {
    /*
     * @base
     */
    color: red;
}

.base-2 {
    /*
     * @base
     */
    padding: 10px;
}

.foo {
    /*
     * @include .base-1, .base-2
     */
    font-size: 12px;
}
```

**Comment by msaktype** [comment]
`postcss-include` must get CSS string as the first argument to parse the CSS.
https://github.com/morishitter/postcss-include/blob/master/index.js#L3
I have not used to use webpack. But i think, you should the below code.

``` js
require('postcss-include')(app.css)
```

**Comment by apreg** [comment]
It does not work, sorry. I don't know webpack well neither but with a simple `console.log()` I figured out it gets the css but does not write out anything if I insert a `console.log` before `return root`. I have to set up a new debugger then I can tell you more. By the way @include like @extend does delete the @base classes from the source css right? Could it be optional? I don't wanna lose my utility classes 'cause sometimes I need them.

**Comment by msaktype** [comment]
>  @include like @extend does delete the @base classes from the source css right? Could it be optional? I don't wanna lose my utility classes 'cause sometimes I need them.

OK, I'll take this option into consideration :)
But I think, utility classes should be used when be in development. Using `postcss-include`, we can run pre-compile code in browsers because the metadata to transform CSS is in comment as annotations. https://github.com/morishitter/atcss#why-annotations

**Comment by apreg** [comment]
> But I think, utility classes should be used when be in development.

I'm learning [SUITCSS](https://github.com/suitcss/suit) and it looks to me sometimes there is a place for a uitlity class in production according to SUITCSS style guide. 
[When to use a utility](https://github.com/suitcss/suit/issues/40)

Yeah, I've read that part in the atcss documentation but I could not get it, sorry for my dumbness. Why would I run pre-compile code in the browser? And when gets it compiled then? I imagined the way the plugin works is the same as any other css processor. You give a source then it gives an output which gets then served by the server to the client.

**Comment by msaktype** [comment]
In my experience, the products using some utility classes are fragile. Because its name don't have the intent of the design. For example, utility class named as `.pdt-10` means only `padding-top: 10px`. `pdt-10` don't have the intent, "Why do you want `padding-top: 10px` to the contents?". But I think, utility classes are necessary in development. Because using utility classes, we can design in the browser fast.

> Why would I run pre-compile code in the browser? 

In development I want to use utility classes (the classes that don't named semantic). But in production, semantic class name is better. For example, `class="btn-next"` is better than `class="btn btn-primary btn-large"` if the button is to go to next page.

> And when gets it compiled then?

Before release in production.

**Comment by msaktype** [comment]
In v0.3.0, this probrem is solved.
